# Site settings
baseurl = "http://my-awesome-site.com/"
languageCode = "en-us"
title = "Bryce Bartlett"
theme = "freelance-mod"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Bryce Bartlett"
    description = ""

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "your@email.com"

    [params.navigation]
        brand = "Home"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "ibjb40.jpg"
        name = "Bryce Bartlett"
        subtitle = "Health *  Data Science * Law"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "My Work"

        [params.portfolio.modal]
            
            category = "Categories"
            buttontext = "Close"


    [params.about]
        title = "About"
        
        left = "I am a PhD Candidate at Duke University, affiliated with the [Sociology Department](http://sociology.duke.edu) and two interdisciplinary centers: the [Social Science Research Institute](https://ssri.duke.edu/) and the [Duke Population Research Institute](https://dupri.duke.edu/). My research is supported by an NIA training grant."
        right = "I use data to explore the changes in populations and population health. I am especially interested how law and policy impact these changes. Download a copy of my cv [here](cv/cv.pdf), and explore summaries of my work below."




    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."



        [params.footer.social]
            title = "Social Media"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/bjb40"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//www.linkedin.com/in/bryce-bartlett-0980822"

         [[params.footer.social.networks]]
                icon = "fa-user"
                link=  "//ssrn.com/author=914650"